let mock = {
    flits: [
        {
            id: 1,
            flit: "why don't i live here",
            date: "3/18/2021",
            userId: 6,
            image: "https://img.huffingtonpost.com/asset/568ec12e1b00002d00674f0e.jpeg?ops=scalefit_960_noupscale",
        },
        {
            id: 2,
            flit: "I want winter to be over.",
            date: "3/18/2021",
            userId: 2,
            image: "",
        },
        {
            id: 3,
            flit: "Daylight savings is the worst",
            date: "3/17/2021",
            userId: 3,
            image: "",
        },
        {
            id: 4,
            flit: "my alarm didn't go off and I missed all my classes. nice.",
            date: "3/17/2021",
            userId: 14,
            image: "",
        },
        {
            id: 5,
            flit: "why isn't it christmas all the time",
            date: "3/17/2021",
            userId: 7,
            image: "",
        },
        {
            id: 6,
            flit: "i don't want to get up today",
            date: "3/17/2021",
            userId: 5,
            image: "",
        },
        {
            id: 7,
            flit: "i thought i looked cool",
            date: "3/16/2021",
            userId: 7,
            image: "https://www.snowskool.com/uploads/images/Intermediate_to_Advanced_Boarding.jpg",
        },
        {
            id: 8,
            flit: "ice cream is the best food hands down",
            date: "3/16/2021",
            userId: 5,
            image: "",
        },
        {
            id: 9,
            flit: "do you guys remember this",
            date: "3/16/2021",
            userId: 6,
            image: "https://i.pinimg.com/originals/41/66/0b/41660bbaea604cf4c82cae29a631488c.jpg",
        },
        {
            id: 10,
            flit: "i'm so tired",
            date: "3/16/2021",
            userId: 12,
            image: "",
        },
        {
            id: 11,
            flit: "you just lost the game",
            date: "3/16/2021",
            userId: 1,
            image: "",
        },
        {
            id: 12,
            flit: "IHOP has never let me down",
            date: "3/18/2021",
            userId: 1,
            image: "https://www.recipetineats.com/wp-content/uploads/2017/06/Pancakes-SQ.jpg",
        },
        {
            id: 13,
            flit: "i either sleep for 2 hours or 12 there is no in between",
            date: "3/15/2021",
            userId: 1,
            image: "",
        },
    ],
    users: [
        {
            id: 1,
            name: "Aleah Fredrickson",
            handle: "@aleahfredrickson",
            image: "https://cdn1.iconfinder.com/data/icons/avatars-1-5/136/87-512.png",
        },
        {
            id: 2,
            name: "John Smith",
            handle: "@johnsmith",
            image: "https://www.kindpng.com/picc/m/22-223941_transparent-avatar-png-male-avatar-icon-transparent-png.png",
        },
        {
            id: 3,
            name: "Sarah Adams",
            handle: "@sarahadams",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
        },
        {
            id: 4,
            name: "Kylie Sanders",
            handle: "@kyliesanders",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
        },
        {
            id: 5,
            name: "Emily Barnes",
            handle: "@emilybarnes",
            image: "https://icon-library.com/images/anonymous-female-icon/anonymous-female-icon-15.jpg",
        },
        {
            id: 6,
            name: "Sam Johnson",
            handle: "@samjohnson",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
        },
        {
            id: 7,
            name: "Ben Walker",
            handle: "@benwalker",
            image: "https://dizitalsquare.com/wp-content/uploads/2018/07/Male-Avatar.png",
        },
        {
            id: 8,
            name: "Julie West",
            handle: "@juliewest",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
        },
        {
            id: 9,
            name: "Jake Gardner",
            handle: "@jakegardner",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
        },
        {
            id: 10,
            name: "Andrew Phillips",
            handle: "@andrewphillips",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
        },
        {
            id: 11,
            name: "Chloe White",
            handle: "@chloewhite",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
        },
        {
            id: 12,
            name: "Amy Miller",
            handle: "@amymiller",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
        },
        {
            id: 13,
            name: "Peyton Jones",
            handle: "@peytonjones",
            image: "https://i2.wp.com/nofiredrills.com/wp-content/uploads/2016/10/myavatar.png?fit=400%2C400&ssl=1",
        },
        {
            id: 14,
            name: "Aaron Stark",
            handle: "@aaronstark",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoGa43cPo70DYcZ847mc02nOf8y0r9nJ38WQ&usqp=CAU",
        },
        {
            id: 15,
            name: "Caroline Collins",
            handle: "@carolinecollins",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png",
        },
    ],
    currUser: {
        id: 1,
    }
}

export default mock